remote_theme: aditya-shri/just-the-docs
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
color_scheme: dark
#logo: "/img/java.png"

collections:
  Abstraction:
    permalink: "/:collection/:path/"
    output: true
  Arrays:
    permalink: "/:collection/:path/"
    output: true
  Collections:
    permalink: "/:collection/:path/"
    output: true
  ControlStatement:
    permalink: "/:collection/:path/"
    output: true
  DataType:
    permalink: "/:collection/:path/"
    output: true
  Encapsulation:
    permalink: "/:collection/:path/"
    output: true
  Enumeration:
    permalink: "/:collection/:path/"
    output: true
  Exception:
    permalink: "/:collection/:path/"
    output: true
  Inheritance:
    permalink: "/:collection/:path/"
    output: true
  InnerClass:
    permalink: "/:collection/:path/"
    output: true
  Iterative:
    permalink: "/:collection/:path/"
    output: true
  Keywords:
    permalink: "/:collection/:path/"
    output: true
  Multithreading:
    permalink: "/:collection/:path/"
    output: true
  OopsConcept:
    permalink: "/:collection/:path/"
    output: true
  Operators:
    permalink: "/:collection/:path/"
    output: true
  Polymorphism:
    permalink: "/:collection/:path/"
    output: true
  Regex:
    permalink: "/:collection/:path/"
    output: true
  Strings:
    permalink: "/:collection/:path/"
    output: true
  swings:
    permalink: "/:collection/:path/"
    output: true
  Variables:
    permalink: "/:collection/:path/"
    output: true
  
collections_dir: src
    
just-the-docs:
    collections:
          Abstraction:
            name: Abstraction
            output: true
            nav_exclude: false
            search_exclude: false
          Arrays:
            name: Arrays
            nav_exclude: false
            search_exclude: false
          Collections:
            name: Collections
            nav_exclude: false
            search_exclude: false
          ControlStatement:
            name: ControlStatement
            nav_exclude: false
            search_exclude: false
          DataType:
            name: DataType
            nav_exclude: false
            search_exclude: false
          Encapsulation:
            name: Encapsulation
            nav_exclude: false
            search_exclude: false
          Enumeration:
            name: Enumeration
            nav_exclude: false
            search_exclude: false
          Exception:
            name: Exception
            nav_exclude: false
            search_exclude: false
          Inheritance:
            name: Inheritance
            nav_exclude: false
            search_exclude: false
          InnerClass:
            name: InnerClass
            nav_exclude: false
            search_exclude: false
          Iterative:
            name: Iterative
            nav_exclude: false
            search_exclude: false
          Keywords:
            name: Keywords
            nav_exclude: false
            search_exclude: false
          Multithreading:
            name: Multithreading
            nav_exclude: false
            search_exclude: false
          OopsConcept:
            name: OopsConcept
            nav_exclude: false
            search_exclude: false
          Operators:
            name: Operators
            nav_exclude: false
            search_exclude: false
          Polymorphism:
            name: Polymorphism
            nav_exclude: false
            search_exclude: false
          Regex:
            name: Regex
            nav_exclude: false
            search_exclude: false
          Strings:
            name: Strings
            nav_exclude: false
            search_exclude: false
          swings:
            name: swings
            nav_exclude: false
            search_exclude: false
          Variables:
            name: Variables
            nav_exclude: false
            search_exclude: false