#theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
color_scheme: dark

collections_dir: src

collections:
  Abstraction:
    output: true