#theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
color_scheme: dark

collections:
    src:
        permalink: "./src/"
        output: true

just_the_docs:
    collections:
        src:
            name: Home
            nav_exclude: false
            search_exclude: false