#theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
color_scheme: dark

collections:
  Abstraction:
    permalink: "/:collection/:path/"
    output: true
collections_dir: docs
    
just-the-docs:
    collections:
        Abstraction:
          name: Abstraction
          nav_exclude: false
          search_exclude: false