#theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
color_scheme: dark

collections:
  docs:
    permalink: "/_Abstraction/abstractClass"
    output: true
    
just-the-docs:
    collections:
        docs:
          name: Abstraction
          nav_exclude: false
          search_exclude: false